import { AbilityCategory, Spheres } from "../StatOutline";

const Constants = {
  ArchetypesArray: [
    "Activist",
    "Architect",
    "Artist",
    "Benefactor",
    "Bon Vivant",
    "Caregiver",
    "Conformist",
    "Contrary",
    "Crusader",
    "Director",
    "Entertainer",
    "Guardian",
    "Hacker",
    "Heretic",
    "Mentor",
    "Idealist",
    "Innovator",
    "Romantic",
    "Kid",
    "Loner",
    "Machine",
    "Mad Scientist",
    "Martyr",
    "Monster",
    "Prophet",
    "Rogue",
    "Sensualist",
    "Survivor",
    "Traditionalist",
    "Trickster",
    "Tycoon",
    "Vigilante",
    "Visionary",
    "Zealot",
  ],
  Essences: ["Primordial", "Dynamic", "Pattern", "Questing"],
  Affiliations: [
    "Tradition",
    "Nephandi",
    "Technocracy",
    "Disparate",
    "Marauder",
  ],
  TraditionSects: [
    "Akashayana",
    "Celestial Chorus",
    "Cult of Ecstacy",
    "Dreamspeaker",
    "Euthanatoi",
    "Hermic Order",
    "Society of Ether",
    "Verbena",
    "Virtual Adepts",
  ],
  NephandiSects: ["Infernalist", "Malfean", "K'llasshaa"],
  TechnocracySects: [
    "Iteration X",
    "New World Order",
    "Progenitor",
    "Syndicate",
    "Void Engineer",
  ],
  DisparateSects: [
    "Orphan",
    "Hollow Ones",
    "Ahl-i-Batin",
    "Taftâni",
    "Sisters of Hippolyta",
    "Knights Templar",
    "Wu-Keng",
    "Lions of Zion",
    "Wu Nung",
    "Thunder Society",
    "Navalon",
    "Miranohmen",
    "Red Thorn Dedicants",
    "Its'at",
  ],
  Stats: {
    Arete: 0,
    Willpower: 0,
    Spheres: [
      { Correspondence: 0 },
      { Entropy: 0 },
      { Forces: 0 },
      { Life: 0 },
      { Matter: 0 },
      { Mind: 0 },
      { Prime: 0 },
      { Spirit: 0 },
      { Time: 0 },
    ],
    Backgrounds: [{}],
  },
};

export const mageTalents: AbilityCategory = {
  name: "Talents",
  enabledStats: [
    { name: "Alertness", level: 0, specialty: null, enabled: true },
    { name: "Art", level: 0, specialty: null, enabled: true },
    { name: "Athletics", level: 0, specialty: null, enabled: true },
    { name: "Awareness", level: 0, specialty: null, enabled: true },
    { name: "Brawl", level: 0, specialty: null, enabled: true },
    { name: "Empathy", level: 0, specialty: null, enabled: true },
    { name: "Expression", level: 0, specialty: null, enabled: true },
    { name: "Intimidation", level: 0, specialty: null, enabled: true },
    { name: "Leadership", level: 0, specialty: null, enabled: true },
    { name: "Streetwise", level: 0, specialty: null, enabled: true },
    { name: "Subterfuge", level: 0, specialty: null, enabled: true },
  ],
  disabledStats: [],
};
export const mageSkills: AbilityCategory = {
  name: "Skills",
  enabledStats: [
    { name: "Crafts", level: 0, specialty: null, enabled: true },
    { name: "Drive", level: 0, specialty: null, enabled: true },
    { name: "Ettiquitte", level: 0, specialty: null, enabled: true },
    { name: "Firearms", level: 0, specialty: null, enabled: true },
    { name: "MartialArts", level: 0, specialty: null, enabled: true },
    { name: "Meditation", level: 0, specialty: null, enabled: true },
    { name: "Melee", level: 0, specialty: null, enabled: true },
    { name: "Research", level: 0, specialty: null, enabled: true },
    { name: "Stealth", level: 0, specialty: null, enabled: true },
    { name: "Survival", level: 0, specialty: null, enabled: true },
    { name: "Technology", level: 0, specialty: null, enabled: true },
  ],
  disabledStats: [],
};
export const mageKnowledges: AbilityCategory = {
  name: "Knowledges",
  enabledStats: [
    { name: "Academics", level: 0, specialty: null, enabled: true },
    { name: "Computer", level: 0, specialty: null, enabled: true },
    { name: "Cosmology", level: 0, specialty: null, enabled: true },
    { name: "Enigmas", level: 0, specialty: null, enabled: true },
    { name: "Esoterica", level: 0, specialty: null, enabled: true },
    { name: "Investigation", level: 0, specialty: null, enabled: true },
    { name: "Law", level: 0, specialty: null, enabled: true },
    { name: "Medicine", level: 0, specialty: null, enabled: true },
    { name: "Occult", level: 0, specialty: null, enabled: true },
    { name: "Politics", level: 0, specialty: null, enabled: true },
    { name: "Science", level: 0, specialty: null, enabled: true },
  ],
  disabledStats: [],
};
export const traditionSpheres: Spheres = {
  enabledSpheres: [
    { name: "Correspondance", level: 0 },
    { name: "Entropy", level: 0 },
    { name: "Forces", level: 0 },
    { name: "Life", level: 0 },
    { name: "Matter", level: 0 },
    { name: "Mind", level: 0 },
    { name: "Prime", level: 0 },
    { name: "Spirit", level: 0 },
    { name: "Time", level: 0 },
  ],
  disabledSpheres: [
    { name: "Data", level: 0 },
    { name: "Dimensional Science", level: 0 },
    { name: "Primal Utility", level: 0 },
  ],
};

export const technocratSpheres: Spheres = {
  enabledSpheres: [
    { name: "Data", level: 0 },
    { name: "Entropy", level: 0 },
    { name: "Forces", level: 0 },
    { name: "Life", level: 0 },
    { name: "Matter", level: 0 },
    { name: "Mind", level: 0 },
    { name: "Primal Utility", level: 0 },
    { name: "Dimensional Science", level: 0 },
    { name: "Time", level: 0 },
  ],
  disabledSpheres: [
    { name: "Correspondance", level: 0 },
    { name: "Prime", level: 0 },
    { name: "Spirit", level: 0 },
  ],
};
export default Constants;
