const Constants = {
  ArchetypesArray: [
    "Activist",
    "Architect",
    "Artist",
    "Benefactor",
    "Bon Vivant",
    "Caregiver",
    "Conformist",
    "Contrary",
    "Crusader",
    "Director",
    "Entertainer",
    "Guardian",
    "Hacker",
    "Heretic",
    "Mentor",
    "Idealist",
    "Innovator",
    "Romantic",
    "Kid",
    "Loner",
    "Machine",
    "Mad Scientist",
    "Martyr",
    "Monster",
    "Prophet",
    "Rogue",
    "Sensualist",
    "Survivor",
    "Traditionalist",
    "Trickster",
    "Tycoon",
    "Vigilante",
    "Visionary",
    "Zealot",
  ],
  Essences: ["Primordial", "Dynamic", "Pattern", "Questing"],
  Affiliations: [
    "Tradition",
    "Nephandi",
    "Technocracy",
    "Disparate",
    "Marauder",
  ],
  TraditionSects: [
    "Akashayana",
    "Celestial Chorus",
    "Cult of Ecstacy",
    "Dreamspeaker",
    "Euthanatoi",
    "Hermic Order",
    "Society of Ether",
    "Verbena",
    "Virtual Adepts",
  ],
  NephandiSects: ["Infernalist", "Malfean", "K'llasshaa"],
  TechnocracySects: [
    "Iteration X",
    "New World Order",
    "Progenitor",
    "Syndicate",
    "Void Engineer",
  ],
  DisparateSects: [
    "Orphan",
    "Hollow Ones",
    "Ahl-i-Batin",
    "Taftâni",
    "Sisters of Hippolyta",
    "Knights Templar",
    "Wu-Keng",
    "Lions of Zion",
    "Wu Nung",
    "Thunder Society",
    "Navalon",
    "Miranohmen",
    "Red Thorn Dedicants",
    "Its'at",
  ],
  Stats: [
    {
      key: "Attributes",
      value: [
        {
          key: "Physical",
          value: [
            { key: "Strength", value: 0 },
            { key: "Dexterity", value: 0 },
            { key: "Stamina", value: 0 },
          ],
        },
        {
          key: "Social",
          value: [
            { key: "Charisma", value: 0 },
            { key: "Manipulation", value: 0 },
            { key: "Appearance", value: 0 },
          ],
        },
        {
          key: "Mental",
          value: [
            { key: "Perception", value: 0 },
            { key: "Intelligence", value: 0 },
            { key: "Wits", value: 0 },
          ],
        },
      ],
    },
    {
      key: "Abilities",
      value: [
        {
          key: "Talents",
          value: [
            { key: "Alertness", value: 0 },
            { key: "Art", value: 0 },
            { key: "Athletics", value: 0 },
            { key: "Awareness", value: 0 },
            { key: "Brawl", value: 0 },
            { key: "Empathy", value: 0 },
            { key: "Expression", value: 0 },
            { key: "Intimidation", value: 0 },
            { key: "Leadership", value: 0 },
            { key: "Streetwise", value: 0 },
            { key: "Subterfuge", value: 0 },
          ],
        },
        {
          key: "Skills",
          value: [
            { key: "Crafts", value: 0 },
            { key: "Drive", value: 0 },
            { key: "Ettiquitte", value: 0 },
            { key: "Firearms", value: 0 },
            { key: "Martial Arts", value: 0 },
            { key: "Meditation", value: 0 },
            { key: "Melee", value: 0 },
            { key: "Research", value: 0 },
            { key: "Stealth", value: 0 },
            { key: "Survival", value: 0 },
            { key: "Technology", value: 0 },
          ],
        },
        {
          key: "Knowledges",
          value: [
            { key: "Academics", value: 0 },
            { key: "Computer", value: 0 },
            { key: "Cosmology", value: 0 },
            { key: "Enigmas", value: 0 },
            { key: "Esoterica", value: 0 },
            { key: "Investigation", value: 0 },
            { key: "Law", value: 0 },
            { key: "Medicine", value: 0 },
            { key: "Occult", value: 0 },
            { key: "Politics", value: 0 },
            { key: "Science", value: 0 },
          ],
        },
      ],
    },

    { key: "Arete", value: 0 },
    { key: "Willpower", value: 0 },
    {
      key: "Spheres",
      value: [
        { key: "Correspondence", value: 0 },
        { key: "Entropy", value: 0 },
        { key: "Forces", value: 0 },
        { key: "Life", value: 0 },
        { key: "Matter", value: 0 },
        { key: "Mind", value: 0 },
        { key: "Prime", value: 0 },
        { key: "Spirit", value: 0 },
        { key: "Time", value: 0 },
      ],
    },
    { key: "Backgrounds", value: [{ key: "" }] },
  ],
};

export default Constants;
